version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - python -m pdoc --docformat google --output-directory $READTHEDOCS_OUTPUT/html tinypg

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
